# yaml-language-server: $schema=http://json-schema.org/draft-07/schema#
title: Tiled Text Object
description: Schema for a Text object within Tiled.
type: object
properties:
  bold:
    type: boolean
    default: false
    description: 'Whether to use a bold font (default: `false`)'
  color:
    type: string
    pattern: ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$
    default: '#000000'
    description: 'Hex-formatted color (#RRGGBB or #AARRGGBB) (default: `#000000`)'
  fontfamily:
    type: string
    default: sans-serif
    description: 'Font family (default: `sans-serif`)'
  halign:
    type: string
    enum:
    - center
    - right
    - justify
    - left
    default: left
    description: Horizontal alignment (`center`, `right`, `justify` or `left` (default))
  italic:
    type: boolean
    default: false
    description: 'Whether to use an italic font (default: `false`)'
  kerning:
    type: boolean
    default: true
    description: 'Whether to use kerning when placing characters (default: `true`)'
  pixelsize:
    type: integer
    default: 16
    description: 'Pixel size of font (default: 16)'
  strikeout:
    type: boolean
    default: false
    description: 'Whether to strike out the text (default: `false`)'
  text:
    type: string
    description: Text
  underline:
    type: boolean
    default: false
    description: 'Whether to underline the text (default: `false`)'
  valign:
    type: string
    enum:
    - center
    - bottom
    - top
    default: top
    description: Vertical alignment (`center`, `bottom` or `top` (default))
  wrap:
    type: boolean
    default: false
    description: 'Whether the text is wrapped within the object bounds (default: `false`)'
required:
- text
