# yaml-language-server: $schema=http://json-schema.org/draft-07/schema#
title: Tiled Tile Layer Chunk
description: Schema for a chunk of tile data in an infinite map. (Inferred from common
  patterns, not explicitly detailed in documentation snippets)
type: object
properties:
  data:
    type: array
    items:
      type: integer
    description: Array of GIDs for the chunk
  height:
    type: integer
    description: Row count of the chunk
  width:
    type: integer
    description: Column count of the chunk
  x:
    type: integer
    description: X coordinate where chunk content starts
  y:
    type: integer
    description: Y coordinate where chunk content starts
required:
- data
- height
- width
- x
- y
