# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
title: Entity Defs
type: object
properties:
  players:
    type: array
    items:
      $ref: ./player.schema.yaml
  mobs:
    type: array
    items:
      $ref: ./mob.schema.yaml
