# yaml-language-server: $schema=http://json-schema.org/draft-07/schema#
title: SchemaIndex
type: object
description: Schema definition that references the various top-level schemas in the
  directory for automation purposes
properties:
  map_data:
    $ref: ./maps/versions/1.11.2_x_1.10/tiled-map.schema.yaml
  game_config:
    $ref: ./game_config.schema.yaml
  ecs:
    $ref: ./ecs/v0.0.1/entity-defs.schema.yaml
automation_config:
  description: Config settings for automation features, not used for actual schema
    definition
