# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
title: GameConfig
description: Main config file for general game options
type: object
properties:
  screen_resolution:
    description: Height/width for the overall screen
    $ref: ./common/common-props.schema.yaml#/definitions/HeightWidthPair
    default:
      width: 640
      height: 480
  screen_mode:
    type: string
    description: Option to set how the game is rendered on screen (fullscreen, borderless
      window, or window)
    enum:
    - fullscreen
    - borderlessWindow
    - window
    default: window
  enabled_mod_ids:
    type: array
    description: List of mod ids that have been manually enabled by the user to be
      loaded into the current game context
    items:
      type: string
required:
- screen_resolution
- screen_mode
- enabled_mod_ids
